---
#kubernetes related vars
kubernetes_release_version: "1.1.2"

kubernetes_binary_package: kubernetes_v{{ kubernetes_release_version }}.tar.gz

kubernetes_download_url: https://github.com/kubernetes/kubernetes/releases/download/v{{ kubernetes_release_version }}/kubernetes.tar.gz

# docker related vars
docker_version: "1.8.2"

docker_package_name: "docker-engine"

docker_registry: "SIDR24APISDP001.dal-na.apm.ibmserviceengage.com:5000"

docker_registry_ca_dir: "SIDR24APISDP001"

#etcd related vars

etcd_version: "2.0.12"

etcd_binary_package: etcd-v{{ etcd_version }}-linux-amd64.tar.gz

etcd_download_url: https://github.com/coreos/etcd/releases/download/v{{ etcd_version }}/etcd-v{{ etcd_version }}-linux-amd64.tar.gz


#flannel related vars
networking: flannel

flannel_etcd_url_scheme: http

flannel_subnet: 172.16.0.0

flannel_prefix: 16

flannel_host_prefix: 24

flannel_backend_type: udp

# should use eth0 as default
flannel_opts: "-iface=eth0 --ip-masq=true"

#kube related vars

kube_service_addresses: 172.17.0.0/16

cluster_name: cluster.local

#iptables or userspace
kube_proxy_mode: "--proxy-mode=iptables --masquerade-all=false"


# ntp server
ntpserver: "10.0.77.54"
