---
# tasks file for registry

- name: Create regstry cert direcotry
  file: path=/etc/docker/certs.d/{{docker_registry}} state=directory
  when: docker_registry != ""

- debug: msg="{{docker_registry_ca_dir}}/ca.crt"

- name: Write ca.crt to docker registry
  copy: src={{docker_registry_ca_dir}}/ca.crt dest=/etc/docker/certs.d/{{docker_registry}}
  notify:
    - restart docker
    
- name: Start kubelet
  service: name=kubelet state=started 