---

- name: Determine if kube common config
  stat: path={{ kube_config_dir }}/config
  register: check_kube_common_configured
  always_run: yes
  
- name: Configure kube common config if it doesn't exist
  template: src={{ kubernetes_release_version }}/config.j2 dest={{ kube_config_dir }}/config
  when: not check_kube_common_configured.stat.exists
  
- name: write the proxy config file for the kube proxy
  template: src={{ kubernetes_release_version }}/proxy.j2 dest={{ kube_config_dir }}/proxy

  
- name: Write kube proxy systemd unit file for centos redhat
  copy: src={{ kubernetes_release_version }}/kube-proxy.service dest=/usr/lib/systemd/system