---
#This playbook deploys a kubernetes cluster

- hosts:
    - all
  serial: 100%
  sudo: yes
  roles:
    - common

- hosts: 
    - kube-masters
    - kube-nodes
  #strategy: free it's only for 2.0.0
  serial: 100%
  sudo: yes
  roles:
    - kubernetes
  tags:
    - install
    
- hosts:
    - kube-nodes
  serial: 100%
  sudo: yes
  roles:
    - docker

# install and configure etcd
- hosts:
    - etcd
  serial: 100%
  sudo: yes
  roles:
    - etcd

# install and configure flannel  
- hosts:
    - kube-nodes
  serial: 100%
  sudo: yes
  roles:
    - flannel
    
    
# install master
- hosts:
    - kube-masters
  serial: 100%
  sudo: yes
  roles:
    - master