---
# tasks file for kubelet

- name: write the common config file for the kubelet
  template: src={{ kubernetes_release_version }}/config.j2 dest={{ kube_config_dir }}/config
  
- name: write the kubelet config file for the kubelet
  template: src={{ kubernetes_release_version }}/kubelet.j2 dest={{ kube_config_dir }}/kubelet
  
- name: reload systemd
  command: systemctl --system daemon-reload

- name: Write kubelet systemd unit file for centos redhat
  copy: src={{ kubernetes_release_version }}/kubelet.service dest=/usr/lib/systemd/system