---
# tasks file for kubelet

- name: Create kubernetes config directory
  file: path={{ kube_config_dir }} state=directory


- name: Determine if kubelet configured
  stat: path=/usr/local/bin/kubelet
  register: check_kubelet_configured
  always_run: yes
  
- name: Configure kublet if it doesn't exist
  include: kubelet.yml
  when: not check_kubelet_configured.stat.exists
 
  
- name: Enable kubelet
  service: name=kubelet enabled=yes state=started