---
# tasks file for etcd installation

- name: Create config directory
  file: path="/etc/etcd" state=directory

- name: Write etcd config file
  template: src={{ etcd_version }}/etcd.conf.j2 dest=/etc/etcd/etcd.conf

- name: Write etcd systemd unit file for centos redhat
  copy: src={{ etcd_version }}/etcd.service dest=/usr/lib/systemd/system
  notify:
    - reload systemd
    - restart etcd

- name: Enable etcd
  service: name=etcd enabled=yes

- name: Start etcd
  service: name=etcd state=started
  register: etcd_started