---
# tasks file for etcd installation

- name: Register tmp etcd tar file
  stat: path=/tmp/.ansible/files/{{etcd_binary_package}}
  register: etcdtmppkg
  
- name: Delete etcd package if it exists
  shell: rm -rf /tmp/.ansible/files/etcd*
  when: not etcdtmppkg.stat.exists
  
- name: Create download dir
  file: path="/tmp/.ansible/files" state=directory

- name: Download tar file
  get_url:
    url: {{etcd_download_url}}
    dest: /tmp/.ansible/files
    #validate_certs: False
  environment:
    http_proxy: "{{ http_proxy|default('') }}"
    https_proxy: "{{ https_proxy|default('') }}"
    

- name: Extract etcd package
  unarchive: src=/tmp/{{kubenetes_binary_package}}
             dest=/tmp/
             copy=no
             
- name: Extract kubernetes binary
  unarchive: src=/tmp/kubernetes/server/kubernetes-server-linux-amd64.tar.gz
             dest=/tmp/kubernetes/server/
             copy=no
           
- name: Copy kubenetes binary
  shell: find . -executable -type f|grep kube|grep -v kube$| xargs cp -t /usr/local/bin/
  args:
    chdir: /tmp/kubernetes/server/kubernetes/server/bin