---
# tasks file for etcd installation

- name: Register tmp etcd tar file
  stat: path=/tmp/.ansible/files/{{etcd_binary_package}}
  register: etcdtmppkg
  
- name: Delete etcd package if it exists
  shell: rm -rf /tmp/.ansible/files/etcd*
  when: not etcdtmppkg.stat.exists
  
- name: Create download dir
  file: path="/tmp/.ansible/files" state=directory

- name: Download tar file
  get_url:
    url: "{{etcd_download_url}}"
    dest: /tmp/.ansible/files
    validate_certs: no
  environment:
    http_proxy: "{{ http_proxy|default('') }}"
    https_proxy: "{{ https_proxy|default('') }}"
    

- name: Extract etcd package
  unarchive:
    src: "/tmp/.ansible/files/{{etcd_binary_package}}"
    dest: /tmp/.ansible/files
    copy: no
           
- name: Copy etcd binary
  shell: cp /tmp/.ansible/files/etcd-v{{ etcd_version }}-linux-amd64/{{ item }} /usr/local/bin/{{item}}
  with_items:
    - etcd
    - etcdctl