---
# tasks file for etcd

- name: Determine if etcd installed
  stat: path=/usr/local/bin/etcd
  register: check_etcd_installed
  always_run: yes
  
- name: Install etcd if it doesn't exist
  include: install_etcd.yml
  when: not check_etcd_installed.stat.exists
  

- name: Determine if etcd configured
  stat: path=/usr/lib/systemd/system/etcd.service
  register: check_etcd_configured
  always_run: yes
  
- name: Configure etcd if it doesn't exist
  include: configure_etcd.yml
  when: not check_etcd_configured.stat.exists
  
- name: start etcd
  service: name=etcd state=started