---
# tasks file for kubernetes

- name: Determine if Kube installed
  stat: path=/usr/local/bin/kubelet
  register: check_kube_installed
  always_run: yes
  
- name: Install kube if it doesn't exist
  include: install_kube.yml
  when: not check_kube_installed.stat.exists
  #tags: install