---
# tasks file for flannel configuration

- name: Write Flannel config file
  template: src={{ flannel_version }}/flanneld.j2 dest=/etc/sysconfig/flanneld
    
- name: Write flannel systemd unit file for centos redhat
  copy: src={{ flannel_version }}/flanneld.service dest=/usr/lib/systemd/system
  notify:
    - start Flannel
    - enable Flannel
    - reload systemd
    - configure and start docker

    
  