---
# tasks file for flannel

- name: Determine if etcd flannel config enabled
  shell: "curl -L {{flannel_etcd_url_scheme}}://{{ groups['etcd'][0] }}:2379/v2/keys/coreos.com/network"
  register: check_flannel_not_configured
  run_once: true
  
- debug: msg="curl -L {{flannel_etcd_url_scheme}}://{{ groups['etcd'][0] }}:2379/v2/keys/coreos.com/network"

- debug: msg={{check_flannel_not_configured}}

- name: Configure flannel in etcd server
  include: network_config.yml
  when:  "'Key not found' in check_flannel_not_configured"
    
- name: Determine if flannel installed
  stat: path=/usr/local/bin/flanneld
  register: check_flannel_installed
  always_run: yes
  
- name: Install flannel if it doesn't exist
  include: install_flannel.yml
  when: (not check_flannel_installed.stat.exists) and (inventory_hostname in groups['kube-nodes'])
  tags: install
  
- name: Determine if flannel configured
  stat: path=/usr/lib/systemd/system/flanneld.service
  register: check_flannel_configured
  
- name: Configure flannel if it doesn't exist
  include: configure_flannel.yml
  #when: not check_flannel_configured.stat.exists