---
# tasks file for flannel

- name: Determine if etcd flannel config enabled
  shell: curl -L {{flannel_etcd_url_scheme}}://{{ groups['etcd'][0] }}:2379/v2/keys/coreos.com/network | grep "Key not found"
  register: check_flannel_not_configured
  always_run: yes

- name: Configure flannel in etcd server
  include: etcd_config.yml
  when:  check_flannel_not_configured != ""
    
- name: Determine if flannel installed
  stat: path=/usr/local/bin/flanneld
  register: check_flannel_installed
  always_run: yes
  
- name: Install flannel if it doesn't exist
  include: install_flannel.yml
  when: (not check_flannel_installed.stat.exists) and (inventory_hostname in groups['kube-nodes'])
  tags: install
   
- name: Enable Flannel
  service: name=flanneld enabled=yes
  notify:
    - start flanneld