---
# tasks file for common

- name: "Build hosts file"
  lineinfile: dest=/etc/hosts regexp='^{{ item }}.*' line="{{ hostvars[item].ansible_default_ipv4.address }} {{hostvars[item].ansible_fqdn}} {{hostvars[item].ansible_hostname}}" state=present
  when: hostvars[item].ansible_default_ipv4.address is defined
  with_items: groups['all']

- name: "Install ntp"
  yum: name=ntp state=present
  
  
- name: "sync time"
  shell: ntpdate {{ntpserver}}
  when: ntpserver != ""