---
# tasks file for master

  
- name: Add kube group
  group: name=kube system=yes
#  run_once: true
  
- name: Add kube user
  user: name=kube system=yes shell=/sbin/nologin comment="Kubernetes user" group=kube home=/
#  run_once: true

  