---
  
- name: Install openssl
  yum: name=openssl state=latest
  
- name: Install curl
  yum: name=curl state=present

- name: HACK | overwrite make-ca-cert.sh from local copy
  copy:
    src=make-ca-cert.sh
    dest={{ kube_script_dir }}
    mode=0500
  changed_when: false
  
- debug: msg={{ groups['kube-masters'][0].ansible_hostname }}

- name: Run create cert script on master
  command:
    "{{ kube_script_dir }}/make-ca-cert.sh"
  args:
    creates: "{{ kube_cert_dir }}/server.crt"
  environment:
    MASTER_IP: "{{ kube_cert_ip }}"
    MASTER_NAME: "{{ groups['kube-masters'][0].ansible_hostname }}"
    DNS_DOMAIN: "{{ dns_domain }}"
    SERVICE_CLUSTER_IP_RANGE: "{{ kube_service_addresses }}"
    CERT_DIR: "{{ kube_cert_dir }}"
    CERT_GROUP: "kube"
    HTTP_PROXY: "{{ http_proxy|default('') }}"
    HTTPS_PROXY: "{{ https_proxy|default('') }}"

- name: Verify certificate permissions
  file:
    path={{ item }}
    group=kube
    owner=kube
    mode=0440
  with_items:
    - "{{ kube_cert_dir }}/ca.crt"
    - "{{ kube_cert_dir }}/server.crt"
    - "{{ kube_cert_dir }}/server.key"
    - "{{ kube_cert_dir }}/kubecfg.crt"
    - "{{ kube_cert_dir }}/kubecfg.key"
