---
# tasks file for master

  
- name: Add kube group
  group: name=kube system=yes
#  run_once: true
  
- name: Add kube user
  user: name=kube system=yes shell=/sbin/nologin comment="Kubernetes user" group=kube home=/
#  run_once: true

- name: Determine if general config done
  stat: path={{kube_config_dir}}/config
  register: check_kube_global_configured
  
- name: Generate config if it doesn't exist
  include: config.yml
  when: not check_kube_global_configured.stat.exists

- name: Determine if certificate configured
  stat: path={{ kube_cert_dir }}/ca.crt
  register: check_ca_configured
  
- name: Configure certificate if it doesn't exist
  include: secrets.yml
  when: not check_ca_configured.stat.exists