---
# tasks file for master
- name: Add kube group
  group: name=kube system=yes
  
- name: Add kube user
  user: name=kube system=yes shell=/sbin/nologin comment="Kubernetes user" group=kube home=/

- name: Download kubernetes package
  get_url: >
    url=https://github.com/kubernetes/kubernetes/releases/download/v{{ kubernetes_release_version }}/kubernetes.tar.gz
    dest=/tmp/kubernetes.tar.gz
    

- name: Extract kubernetes package
  unarchive: src=/tmp/kubernetes.tar.gz
             dest=/tmp/
             copy=no
             
- name: Extract kubernetes binary
  unarchive: src=/tmp/kubernetes/server/kubernetes-server-linux-amd64.tar.gz
             dest=/tmp/kubernetes/server/
             copy=no
           
- name: Copy kubenetes binary
  shell: find . -executable -type f|grep kube|grep -v kube$| xargs cp -t /usr/bin/
  args:
    chdir: /tmp/kubernetes/server/kubernetes/server/bin
    
  
- name: Install git
  yum: name=git state=present
  
- name: Download contrib
  shell: git clone https://github.com/kubernetes/contrib.git
  args:
    chdir: /tmp/contrib/init/systemd


  