---

- name: make sure the certificate directory exits
  file:
    path={{ kube_cert_dir }}
    state=directory
    mode=o-rwx
    group=kube

- include: gen_certs.yml
  when: inventory_hostname == groups['kube-masters'][0]

