---
# tasks file for docker

# For now only support centos, redhat and fedora
- name: Determine if Docker installed
  stat: path=/usr/bin/docker
  register: check_docker_installed
  always_run: yes
  
- name: Install docker if it doesn't exist
  include: yum-docker-install.yml
  when: not check_docker_installed.stat.exists
  #tags: install
  
- name: Enable Docker
  service: name=docker enabled=yes
  notify:
    - start docker